#ifndef __MSP_PROCESS_H_
#define __MSP_PROCESS_H_

#define PROCESS_PRIORITY_LEVEL_0       0
#define PROCESS_PRIORITY_LEVEL_1       1
#define PROCESS_PRIORITY_LEVEL_2       2
#define PROCESS_PRIORITY_LEVEL_3       3
#define PROCESS_PRIORITY_LEVEL_5       5
#define PROCESS_PRIORITY_LEVEL_6       6
#define PROCESS_PRIORITY_LEVEL_7       7
#define PROCESS_PRIORITY_LEVEL_8       8
#define PROCESS_PRIORITY_LEVEL_9       9


#endif
