
PROCESS_PATH=$(SOURCE_PATH)/process
FILE_LIST+=source_process_Makefile

#*************************just for test********************#
.PHONY:all
all:
	test -d foldername || mkdir -p foldername
	
.PHONY:clean
clean:

.PHONY: test
test:
	@echo ">>>>source_process_Makefile:$(FILE_LIST)"

