
FILE_LIST+=source_system_Makefile

#*************************just for test********************#
.PHONY:all
all:

.PHONY:clean
clean:

.PHONY: test
test:
	@echo ">>>>source_system_Makefile:$(FILE_LIST)"

