#列出工作目录下所有以“.c”结尾的文件，以空格分隔，将文件列表赋给变量SOURCE
#SOURCE = $(wildcard *.c)
#调用patsubst函数，生成与源文件对应的“.o”文件列表
#OBJECTS = $(patsubst %.c,%.o,$(SOURCE))
#gcc -MM main.c (-MM可以查看main.c的依赖文件)

#***********************************************************#

include base.mk

#**********************************************************#

$(warning,"sdk_Mekefile  start")
#make -C $(PWD)/source
$(warning,"sdk_Mekefile  end")




